[build]
builder = "RAILPACK"

[build.buildCommand]
command = "pnpm install && npx puppeteer browsers install chrome && pnpm run build"

[deploy]
startCommand = "node build/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheckPath]
path = "/"

[deploy.healthcheckTimeout]
timeout = 300
