import { json } from '@sveltejs/kit';
import { handlePaystackWebhook } from '$lib/server/webhook-handler';
import { db } from '$lib/server/db';
import { orders, reports, lookups } from '$lib/server/db/schema';
import { eq } from 'drizzle-orm';
import type { RequestHandler } from '@sveltejs/kit';

export const POST: RequestHandler = async ({ request }) => {
	const signature = request.headers.get('x-paystack-signature') || '';
	const rawBody = await request.text();
	
	console.log('📥 Webhook received:', {
		hasSignature: !!signature,
		bodyLength: rawBody.length
	});
	
	let payload;
	try {
		payload = JSON.parse(rawBody);
		console.log('📦 Webhook event:', payload.event);
	} catch (error) {
		console.error('❌ Failed to parse webhook payload:', error);
		return json({ status: 'received' });
	}

	const result = await handlePaystackWebhook(rawBody, signature, payload);

	console.log('✅ Webhook validation result:', { valid: result.valid, txRef: result.txRef });

	// Always return 200
	if (!result.valid) {
		console.log('⚠️ Invalid webhook, ignoring');
		return json({ status: 'received' });
	}

	try {
		// Find order
		const order = await db.select().from(orders).where(eq(orders.paymentRef, result.txRef!)).limit(1);

		if (order.length === 0) {
			console.log('⚠️ Order not found for reference:', result.txRef);
			return json({ status: 'received' });
		}

		const orderRecord = order[0];
		console.log('📋 Order found:', { id: orderRecord.id, status: orderRecord.status });

		// Check amount
		if (Number(orderRecord.amountNgn) !== result.amount) {
			console.log('⚠️ Amount mismatch:', { expected: orderRecord.amountNgn, received: result.amount });
			return json({ status: 'received' });
		}

		// Update order
		await db
			.update(orders)
			.set({
				status: 'paid',
				paymentId: result.txId,
				paidAt: new Date()
			})
			.where(eq(orders.id, orderRecord.id));

		console.log('✅ Order updated to paid');

		// Check if report exists (idempotency)
		const existingReport = await db
			.select()
			.from(reports)
			.where(eq(reports.orderId, orderRecord.id))
			.limit(1);

		if (existingReport.length > 0) {
			console.log('ℹ️ Report already exists, skipping generation');
			return json({ status: 'received' });
		}

		// Get lookup data
		const lookup = await db
			.select()
			.from(lookups)
			.where(eq(lookups.id, orderRecord.lookupId))
			.limit(1);

		if (lookup.length === 0) {
			console.log('⚠️ Lookup not found:', orderRecord.lookupId);
			return json({ status: 'received' });
		}

		const lookupData = lookup[0];
		const vin = lookupData.vin;

		console.log('📄 Initiating queue-based report generation for VIN:', vin);

		// Trigger queue-based report generation pipeline
		const { getQueue } = await import('$lib/server/queue');
		const { Jobs } = await import('$lib/server/queue/job-names');
		
		try {
			const queue = await getQueue();

			// Define all jobs
			const allJobs = [
				Jobs.FETCH_NHTSA_DECODE,
				Jobs.FETCH_NHTSA_RECALLS,
				Jobs.FETCH_NMVTIS,
				Jobs.FETCH_NICB,
				Jobs.SCRAPE_COPART,
				Jobs.SCRAPE_IAAI,
				Jobs.SCRAPE_AUTOTRADER,
				Jobs.SCRAPE_CARGURUS,
			];

			// Enqueue all jobs - pg-boss will create queues on first send
			console.log('📤 Enqueuing jobs...');
			const results = await Promise.allSettled(
				allJobs.map(jobName => queue.send(jobName, { vin }))
			);

			// Log results
			results.forEach((result, index) => {
				if (result.status === 'fulfilled') {
					console.log(`✓ Enqueued ${allJobs[index]}`);
				} else {
					console.error(`✗ Failed to enqueue ${allJobs[index]}:`, result.reason?.message);
				}
			});

			const successCount = results.filter(r => r.status === 'fulfilled').length;
			console.log(`✅ Enqueued ${successCount}/${allJobs.length} jobs for VIN: ${vin}`);
			console.log('ℹ️ Report will be generated by worker pipeline and delivered when complete');
			
		} catch (error: any) {
			console.error('❌ Failed to enqueue jobs:', error.message);
			// Don't throw - webhook should still return 200
		}

		console.log('🎉 Webhook processing complete');
	} catch (error) {
		console.error('❌ Error processing webhook:', error);
		// Always return 200 to prevent Paystack retries
	}

	return json({ status: 'received' });
};
